### ISSUE TITLE
Can't view source code

### ISSUE THREAD

**Issue by ilkl** [dansomething/coc-java-debug#20]
Coc-java cannot view the source code, but you can view the source code by installing a plug-in vscode-java-decompiler for vscode. Can you write a coc java decompiler plugin based on dgileadi/vscode-java-decompiler?

**Comment by dansomething** [comment]
At the moment I don't have the time to create and support a new plugin. That said, I did take a quick glance at [vscode-java-decompiler](https://github.com/dgileadi/vscode-java-decompiler) and it looks fairly straightforward. It might not take much effort should you or somebody else want to port it to coc.nvim.

**Comment by dansomething** [comment]
Another quick note. Since there doesn't appear to be anything specific to vscode in vscode-java-decompiler, theoretically you could run it along with coc-java by just installing it.

You could add it to your vim runtimepath in your vimrc config.
Something like this:
```
set runtimepath+=/path/to/vscode-java-decompiler
```

Or try installing it with the full GitHub url since it's not in npm:
```
CocInstall https://github.com/dgileadi/vscode-java-decompiler
```

Or try installing with a vim plugin manager:
```
Plug 'dgileadi/vscode-java-decompiler'
```

See the [coc.nvim extensions docs](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions) for all the details on the available installation options.

**Comment by ilkl** [comment]
Thank you very much! I use Plug'dgileadi/vscode-java-decompiler' and it works.
