### ISSUE TITLE
i can't get outputs in watch window

### ISSUE THREAD

**Issue by Xtscat** [dansomething/coc-java-debug#33]
**Versions of relevant software**
 - vim: nvim v0.6.1
 - java: java11
 - maven: 3.8.3

![image](https://user-images.githubusercontent.com/56481656/155947925-16061603-c174-4bfb-914e-e02e5152fa36.png)

here is the messages, they all look good
![image](https://user-images.githubusercontent.com/56481656/155948166-1eb4541a-bf7a-4528-b81c-dbc186235a6b.png)

**Comment by dansomething** [comment]
I was unable to reproduce, but since this project is mainly some simple glue code between [Vimspector](https://github.com/puremourning/vimspector#installation) and the [Java Debug Server](https://github.com/Microsoft/java-debug) extension for [jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) I suspect  it's an issue with one of those. Can you check to make sure you have the latest version of Vimspector, coc-java-debug, coc-java and Eclipse jdt.ls (`:CocCommand java.updateLanguageServer`)?

**Comment by Xtscat** [comment]
I tried these but it just can't worked well. I will try to use nvim-dap. Thanks for help.
