### ISSUE TITLE
Multiple configurations at the same time?

### ISSUE THREAD

**Issue by Frederick888** [dansomething/coc-java-debug#7]
For example selecting from one of the existing configurations when starting?

**Comment by dansomething** [comment]
Fixed in [release 0.1.4](https://github.com/dansomething/coc-java-debug/releases/tag/release%2F0.1.4)

You'll need to set `"java.debug.vimspector.profile": null` and then rely on the built-in Vimspector behavior for [configuration selection](https://puremourning.github.io/vimspector/configuration.html#configuration-selection).

**Comment by dansomething** [comment]
Note, in the next release I'll remove `"java.debug.vimspector.profile"` completely. We can just rely on `"default": true` in the Vimspector.json.
