### ISSUE TITLE
Hot code replace?

### ISSUE THREAD

**Issue by Frederick888** [dansomething/coc-java-debug#9]
Currently after the code is modified I can see `Unhandled event: hotcodereplace`. Is it possible to have HCR in Vim? DCEVM with auto HotSwap works but is usually very resource intensive.

**Comment by dansomething** [comment]
`Unhandled event:...` is coming from [Vimspector](https://github.com/puremourning/vimspector/blob/669b019e25f0ff8999a94bf302c61995687b75e7/python3/vimspector/debug_adapter_connection.py#L278). A hook will need to be added in that project either to handle the event or pass it along to some other custom code that knows how to handle it. There doesn't appear to be much involved in [handling the event](https://github.com/microsoft/vscode-java-debug/blob/master/src/hotCodeReplace.ts#L41) once there is a way to set up the handler.

**Comment by dansomething** [comment]
JRebel is another option if you're willing to pay for it.

**Comment by Frederick888** [comment]
Thanks for your explanation! So I guess this is probably not really related to coc-java-debug or Vimspector? Should I actually file an issue at neoclide/coc-java or eclipse/eclipse.jdt.ls?

**Comment by dansomething** [comment]
It may need to be a new feature in Vimspector to support custom events since the [HotCodeReplaceEvent](https://github.com/microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Events.java#L212) is not in the [Debug Adapter Protocol specification](https://microsoft.github.io/debug-adapter-protocol/specification).

**Comment by Frederick888** [comment]
Thank you. I'll close this ticket in favour of puremourning/vimspector#252 then.
